# Generated by Django 3.2.3 on 2021-05-25 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Equipe',
            new_name='Funcionario',
        ),
        migrations.RenameField(
            model_name='funcionario',
            old_name='name',
            new_name='nome',
        ),
    ]
